apiVersion: v1
kind: Service
metadata:
  name: ghb-dev-helloworld
spec:
  type: NodePort
  ports:
  - name: http
    port: 8090
    nodePort: 30001
    protocol: TCP
  selector:
    app: ghb-dev-helloworld
