apiVersion: v1
kind: Service
metadata:
  name: ghb-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.targetPort }}
    protocol: TCP
  selector:
    app: ghb-app-helloworld
status:
  loadBalancer:
    ingress:
    - ip: 10.104.101.71
