apiVersion: v1
kind: Service
metadata:
  name: ghb-service
spec:
  type: NodePort
  ports:
  - name: node
    port: {{ .Values.containerPort }}
    nodePort: {{ .Values.nodePort }}
    protocol: TCP
  selector:
    app: ghb-dev-helloworld
